from .openaudio_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .openaudio_model_node import NODE_CLASS_MAPPINGS as MODEL_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MODEL_NAME_MAPPINGS
from .openaudio_speaker_node import NODE_CLASS_MAPPINGS as SPEAKER_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPEAKER_NAME_MAPPINGS

# 合并节点映射
ALL_NODE_MAPPINGS = {}
ALL_NODE_MAPPINGS.update(NODE_CLASS_MAPPINGS)
ALL_NODE_MAPPINGS.update(MODEL_NODE_MAPPINGS)
ALL_NODE_MAPPINGS.update(SPEAKER_NODE_MAPPINGS)

ALL_NAME_MAPPINGS = {}
ALL_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS)
ALL_NAME_MAPPINGS.update(MODEL_NAME_MAPPINGS)
ALL_NAME_MAPPINGS.update(SPEAKER_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS = ALL_NODE_MAPPINGS
NODE_DISPLAY_NAME_MAPPINGS = ALL_NAME_MAPPINGS

# 指定Web目录
WEB_DIRECTORY = "./web"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']